import Head from 'next/head';
import Statistics from '../src/components/Statistic';
import { Container } from '@mui/material';
import Header from '../src/components/Header';

export default function Statistic() {
  return (
    <>
      <Head>
        <title>Social Model</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container style={{ marginTop: 100, maxWidth: '100%' }}>
        <Header/>
        <Statistics/>
      </Container>
    </>
  )
}
